version: "3.8"

services:
  freeqy-apis:
    build:
      context: .
      dockerfile: Freeqy-APIs/Dockerfile
    container_name: freeqy-apis
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=EFdb;User Id=sa;Password=Som3a-mssqlserver;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RUN_MIGRATIONS_ON_STARTUP=true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: freeqy-db
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Som3a-mssqlserver
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "pgrep sqlservr > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  sql-data:
