@Freeqy-APIs_HostAddress = https://localhost:7226
@Freeqy_APIs_HostAddress = http://localhost:5030

GET {{Freeqy_APIs_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Freeqy-APIs_HostAddress}}/api/users/me

###

POST {{Freeqy-APIs_HostAddress}}/api/v1/auth/login
Content-Type: application/json
{
  "email": "Freekyadmin@test.com",
  "password": "admiN@123"
}

###
